### ISSUE TITLE
Update Analytics tracking for ecommerce process

### ISSUE THREAD

**Issue by jonathanstegall** [MinnPost/minnpost-membership#38]
- [x] Setup Google analytics to track entire donation flow
- [ ] Track how many people are visiting support page vs. how many people complete the donation
- [ ] Identify what would need to get done in order to track individual actions on the donation page
- [ ] Nice to have: See people going from donation page to the membership level page and if they come back and finish the donation (does their amount of donation change?)

**Comment by jonathanstegall** [comment]
Going to close this for now. We'll revisit if we decide we need to track more.
